{
  # This file is auto-generated by the Katnix installer
  # Machine: Katnix-Desktop
  # Type: desktop
  # Graphics: nvidia
  # Generated: Mon 18 Aug 20:26:50 BST 2025
  
  hostName = "Katnix-Desktop";
  userName = "thealtkitkat";
  userDescription = "Katnix User";
  backgroundImagePath = ../kat.png;
  
  # Hardware imports based on graphics type
  hardwareImports = [
    ../nvidia.nix
  ];
  
  # Machine type configuration (read from persistent config)
  machineType = "desktop";
  includeEliteDangerous = true;
}
