{
  # This file is auto-generated by the Katnix installer
  # Machine: Katnix-Desktop
  # Type: desktop
  # Graphics: Auto-detected
  # Generated: Tue 19 Aug 04:06:43 BST 2025
  
  hostName = "Katnix-Desktop";
  userName = "thealtkitkat";
  userDescription = "Katnix User";
  backgroundImagePath = ../kat.png;
  
  # Hardware imports with universal graphics detection
  hardwareImports = [
    ../universal-graphics.nix
  ];
  
  # Machine type configuration (read from persistent config)
  machineType = "desktop";
  includeEliteDangerous = true;
}
