name: Notify Katnix Machines

on:
  push:
    branches: [ main ]
    paths:
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  notify-machines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get commit info
        id: commit
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date -u +%s)" >> $GITHUB_OUTPUT
          
      - name: Create update notification
        run: |
          cat << EOF > update-notification.json
          {
            "repository": "${{ github.repository }}",
            "commit_sha": "${{ steps.commit.outputs.sha }}",
            "commit_message": "${{ steps.commit.outputs.message }}",
            "author": "${{ steps.commit.outputs.author }}",
            "timestamp": "${{ steps.commit.outputs.timestamp }}",
            "branch": "${{ github.ref_name }}",
            "update_url": "https://github.com/${{ github.repository }}.git"
          }
          EOF
          
      - name: Send webhook to machines
        run: |
          # Send notification to each configured machine
          # This will attempt to notify all machines, but won't fail if some are offline
          
          MACHINES=(
            "katnix-desktop:8080"
            "katnix-laptop:8080" 
            # Add more machines as needed
          )
          
          for machine in "${MACHINES[@]}"; do
            machine_name=$(echo $machine | cut -d: -f1)
            machine_port=$(echo $machine | cut -d: -f2)
            
            echo "Attempting to notify $machine_name..."
            
            # Try to send webhook (don't fail if machine is offline)
            curl -X POST \
              --max-time 10 \
              --connect-timeout 5 \
              --retry 2 \
              --retry-delay 1 \
              --fail-with-body \
              -H "Content-Type: application/json" \
              -H "X-GitHub-Event: push" \
              -H "X-Hub-Signature-256: sha256=${{ secrets.KATNIX_WEBHOOK_SECRET }}" \
              -d @update-notification.json \
              "http://${machine_name}.local:${machine_port}/webhook/katnix-update" \
              || echo "Failed to reach $machine_name (machine may be offline)"
          done
          
      - name: Create fallback notification file
        uses: actions/upload-artifact@v4
        with:
          name: katnix-update-notification
          path: update-notification.json
          retention-days: 7
